# fly.worker.tier2.toml for RQ worker

app = "midjau-worker-tier2"
primary_region = "cdg"

[build]


[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  auto_start_machines = true
  auto_stop_machines = "suspend"
  min_machines_running = 1

